### ISSUE TITLE
Documentation - Create Troubleshooting guide for thundernetes

### ISSUE THREAD

**Issue by AmieDD** [PlayFab/thundernetes#45]
**Is your feature request related to a problem? Please describe.**
A common troubleshooting guide would be helpful for people using thundernetes for common scenarios for specific information pertaining to thundernetes. 

**Describe the solution you'd like**
Add a Troubleshooting guide section for thundernetes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/a

**Comment by dgkanatsios** [comment]
Two items that I can think of:
- what should we do if a GameServer gets stuck? We can advise to `kubectl delete gs <Name>` since this will take down both the GameServer instance, the corresponding Pod as well as the GameServerDetail CRD instance (in case the game server was allocated)
- better document/script the finalizer section here: https://github.com/PlayFab/thundernetes/blob/39f3c8bb3cb4d4f95d128a9700be72cb1014cd21/docs/FAQ.md#deleting-namespace-thundernetes-system-stuck-in-terminating-state

Anything else?
