### ISSUE TITLE
Documentation - Create Prerequisite guide for thundernetes

### ISSUE THREAD

**Issue by AmieDD** [PlayFab/thundernetes#46]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Create a Prerequisite documentation guide for knowledge, tools, and anything pertaining to getting thundernetes up and running.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dgkanatsios** [comment]
Two items that I can think of:
- what should we do if a GameServer gets stuck? We can advise to `kubectl delete gs <Name>` since this will take down both the GameServer instance, the corresponding Pod as well as the GameServerDetail CRD instance (in case the game server was allocated)
- better document/script the finalizer section here: https://github.com/PlayFab/thundernetes/blob/39f3c8bb3cb4d4f95d128a9700be72cb1014cd21/docs/FAQ.md#deleting-namespace-thundernetes-system-stuck-in-terminating-state

**Comment by dgkanatsios** [comment]
draft list that people should have.
- a game server process integrated with GSDK (we can link to the [docs](https://docs.microsoft.com/en-us/gaming/playfab/features/multiplayer/servers/integrating-game-servers-with-gsdk), to the [GSDK repo](https://github.com/PlayFab/gsdk) as well as the [MPSSamples repo](https://github.com/PlayFab/MpsSamples)
- the ability to build a Linux container image with the game server process and assets (so some Docker knowledge as well, maybe we can link [here](https://www.docker.com/101-tutorial))
- a Kubernetes cluster - so some Kubernetes knowledge, maybe we can link [here](https://kubernetes.io/docs/tutorials/kubernetes-basics/)

anything else I'm missing?

**Comment by AmieDD** [comment]
@dgkanatsios I think Prometheus metrics as well?

**Comment by dgkanatsios** [comment]
yuuuuuuup, good catch!
